spring:
  profiles:
    active:
    - dev
---
spring:
  application:
    name: microservicecloud-eureka      #eureka对外暴露的微服务名字  ，会自动转换成大写。
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/clouddb1?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull

mybatis:
  type-aliases-package: com.shp.dev.eureka.model
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      shp:
        dev: debug

server:
  port: 8001
eureka:
  client:
    service-url:  #客户端注册到eureka服务列表内
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept          #修改在注册中心显示的名字
    prefer-ip-address: true   # 访问是现实ip地址


info:
  app.name: servicecould
  company.name: www.shp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$    #以$开头或者结尾的是动态的变量。
---

spring:
  application:
    name: microservicecloud-eureka      #eureka对外暴露的微服务名字  ，会自动转换成大写。
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/clouddb2?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull

mybatis:
  type-aliases-package: com.shp.dev.eureka.model
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      shp:
        dev: debug

server:
  port: 8001
eureka:
  client:
    service-url:  #客户端注册到eureka服务列表内
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept          #修改在注册中心显示的名字
    prefer-ip-address: true   # 访问是现实ip地址


info:
  app.name: servicecould
  company.name: www.shp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$    #以$开头或者结尾的是动态的变量。











